Repository JuliaConstraints/LocalSearchSolvers.jl, pull requests merged in 2021-03, with the labels that each got.

#68 Fix JuMP regression and implements Magic Square
  Project.toml
  src/LocalSearchSolvers.jl
  src/MOI_wrapper/constraints.jl
  src/model.jl
  src/models/magic_square.jl
  src/variable.jl
  test/JuMP.jl
  test/raw_solver.jl
Labels: good first issue, help wanted

#69 Fix JuMP regression and implements Magic Square (#68)
  Project.toml
  src/LocalSearchSolvers.jl
  src/MOI_wrapper/constraints.jl
  src/model.jl
  src/models/magic_square.jl
  src/variable.jl
  test/JuMP.jl
  test/raw_solver.jl
Labels: bug, enhancement

#70 Models
  src/LocalSearchSolvers.jl
  src/models/n_queens.jl
  test/JuMP.jl
Labels: coverage, documentation, enhancement

#85 Updated docs for options
  docs/make.jl
  docs/src/index.md
  docs/src/solving.md
  src/LocalSearchSolvers.jl
  src/options.jl
Labels: documentation

#88 Refactor following the rest of JuliaConstraints
  .github/workflows/ci.yml
Labels: bug, documentation, enhancement
